FROM microsoft/dotnet:latest

# Create a layer that includes cached dependencies :-)
COPY ./DockerStuff/project.json /DockerStuff/project.json
WORKDIR /DockerStuff
RUN ["dotnet", "restore"]

# copy our code
COPY . /app
WORKDIR /app
RUN ["dotnet", "restore"]

# build (speed startup)
WORKDIR /app/Chess.Web
RUN ["dotnet", "build"]

EXPOSE 5000/tcp

ENV ASPNETCORE_ENVIRONMENT Development
ENV ASPNETCORE_URLS http://*:5000

CMD ["dotnet", "run", "--server.urls", "http://0.0.0.0:5000"]

ARG BUILD_DATE
ARG VCS_REF
ARG BUILD_BUILDNUMBER
LABEL org.label-schema.build-date=$BUILD_DATE \
        org.label-schema.name="Chess" \
        org.label-schema.description="Demo Chess site" \
        org.label-schema.vcs-ref=$VCS_REF \
        org.label-schema.vendor="Stuart Leeks" \
        org.label-schema.version=$BUILD_BUILDNUMBER \
        org.label-schema.schema-version="1.0" \
        org.label-schema.vcs-url="https://github.com/stuartleeks/chess" 
#        org.label-schema.url="e.g. https://www.example.com/" \
